MIN_PORT = 1
MAX_PORT = 65535

# The completion arena must hold at least this many slots or three receivers
# cannot pipeline stripes without stalling on slot reuse.
MIN_ARENA_SLOTS = 4

CONFIG_ERROR_EXIT_CODE = 78  # sysexits.h EX_CONFIG

NEXUS_CONFIG_ENV_VAR = "NEXUS_CONFIG"
DEFAULT_CONFIG_PATH = "config.toml"

PROTO_CONTRACT_DIR_ENV_VAR = "NEXUS_PROTO_CONTRACT_DIR"
DEFAULT_PROTO_CONTRACT_DIR = "libs/nexus-proto/proto"

# How long main.py lets a reconnecting receiver say ReceiverHello before
# create_or_adopt decides whether anyone is alive. Fixed, not configurable
# yet: it only matters on the adopt path (a segment already exists), and a
# short bounded wait at startup is a one-time cost, not a steady-state one.
ADOPT_GRACE_PERIOD_SECONDS = 1.5
STARTUP_POLL_INTERVAL_SECONDS = 0.05

PATHS_SECTION = "paths"
SHM_SECTION = "shm"
AGGREGATION_SECTION = "aggregation"
RECEIVERS_SECTION = "receivers"
STATUS_SECTION = "status"

STAGING_DIR_KEY = "staging_dir"
OUTPUT_DIR_KEY = "output_dir"
JOURNAL_DIR_KEY = "journal_dir"
RUN_DIR_KEY = "run_dir"
SOCKET_PATH_KEY = "socket_path"
LOCK_PATH_KEY = "lock_path"

SHM_NAME_KEY = "name"
ARENA_BYTES_KEY = "arena_bytes"
SLOT_BYTES_KEY = "slot_bytes"

POLL_INTERVAL_S_KEY = "poll_interval_s"
STALL_TIMEOUT_S_KEY = "stall_timeout_s"
SHM_CROSSCHECK_KEY = "shm_crosscheck"

RECEIVER_COUNT_KEY = "count"
RECEIVER_PORTS_KEY = "ports"
RECEIVER_BINARY_PATH_KEY = "binary_path"

REFRESH_INTERVAL_S_KEY = "refresh_interval_s"
FORCE_TERMINAL_KEY = "force_terminal"

STAGING_DIR_ENV_VAR = "NEXUS_STAGING_DIR"
OUTPUT_DIR_ENV_VAR = "NEXUS_OUTPUT_DIR"
JOURNAL_DIR_ENV_VAR = "NEXUS_JOURNAL_DIR"
RUN_DIR_ENV_VAR = "NEXUS_RUN_DIR"
SOCKET_PATH_ENV_VAR = "NEXUS_SOCKET_PATH"
LOCK_PATH_ENV_VAR = "NEXUS_LOCK_PATH"

SHM_NAME_ENV_VAR = "NEXUS_SHM_NAME"
ARENA_BYTES_ENV_VAR = "NEXUS_SHM_ARENA_BYTES"
SLOT_BYTES_ENV_VAR = "NEXUS_SHM_SLOT_BYTES"

POLL_INTERVAL_S_ENV_VAR = "NEXUS_AGGREGATION_POLL_INTERVAL_S"
STALL_TIMEOUT_S_ENV_VAR = "NEXUS_AGGREGATION_STALL_TIMEOUT_S"
SHM_CROSSCHECK_ENV_VAR = "NEXUS_AGGREGATION_SHM_CROSSCHECK"

RECEIVER_COUNT_ENV_VAR = "NEXUS_RECEIVERS_COUNT"
RECEIVER_PORTS_ENV_VAR = "NEXUS_RECEIVERS_PORTS"
RECEIVER_BINARY_PATH_ENV_VAR = "NEXUS_RECEIVERS_BINARY_PATH"

REFRESH_INTERVAL_S_ENV_VAR = "NEXUS_STATUS_REFRESH_INTERVAL_S"
FORCE_TERMINAL_ENV_VAR = "NEXUS_STATUS_FORCE_TERMINAL"

DEFAULT_STAGING_DIR = "./staging"
DEFAULT_OUTPUT_DIR = "./output"
DEFAULT_JOURNAL_DIR = "./journal"
DEFAULT_RUN_DIR = "./run"
DEFAULT_SOCKET_PATH = "./run/session-manager.sock"
DEFAULT_LOCK_PATH = "./run/session-manager.lock"

DEFAULT_SHM_NAME = "nexus-rx"
DEFAULT_ARENA_BYTES = 268_435_456
DEFAULT_SLOT_BYTES = 4_194_304

DEFAULT_POLL_INTERVAL_S = 1.0
DEFAULT_STALL_TIMEOUT_S = 8.0
DEFAULT_SHM_CROSSCHECK = True

DEFAULT_RECEIVER_COUNT = 0
DEFAULT_RECEIVER_PORTS: tuple[int, ...] = (9100, 9101, 9102)
DEFAULT_RECEIVER_BINARY_PATH = "./bin/nexus-receiver"

DEFAULT_REFRESH_INTERVAL_S = 0.5
DEFAULT_FORCE_TERMINAL = False

RECEIVER_PORTS_ENV_SEPARATOR = ","
